# F1 Dashboard

In [1]:
import pandas as pd
from glob import glob

from sklearn.utils._repr_html import fitted_attributes

In [2]:
drivers_map = {
    'VER': ('Max Verstappen', 'Red Bull'),
    'GAS': ('Pierre Gasly', 'Alpine'),
    'PER': ('Sergio Perez', 'Red Bull'),
    'ALO': ('Fernando Alonso', 'Aston Martin'),
    'LEC': ('Charles Leclerc', 'Ferrari'),
    'STR': ('Lance Stroll', 'Aston Martin'),
    'MAG': ('Kevin Magnussen', 'Haas'),
    'TSU': ('Yuki Tsunoda', 'Racing Bulls'),
    'ALB': ('Alexander Albon', 'Williams'),
    'ZHO': ('Zhou Guanyu', 'Kick Sauber'),
    'HUL': ('Nico Hulkenberg', 'Haas'),
    'LAW': ('Liam Lawson', 'Racing Bulls'),
    'NOR': ('Lando Norris', 'McLaren'),
    'COL': ('Franco Colapinto', 'Williams'),
    'HAM': ('Lewis Hamilton', 'Mercedes'),
    'SAI': ('Carlos Sainz', 'Ferrari'),
    'DOO': ('Jack Doohan', 'Alpine'),
    'RUS': ('George Russel', 'Mercedes'),
    'BOT': ('Valtteri Bottas', 'Kick Sauber'),
    'PIA': ('Oscar Piastri', 'McLaren'),
    'OCO': ('Esteban Ocon', 'Alpine'),
    'RIC': ('Daniel Ricciardo', 'Racing Bulls'),
    'SAR': ('Logan Sargeant', 'Williams'),
    'BEA': ('Oliver Bearman', 'Haas')
}

In [3]:
f1_team = (
    pd.concat(
        ((pd.read_csv(x)
        .assign(
            track=x.split('/')[1].split('2')[0].replace('_', ' ')
        ) for x in glob('data/*.csv'))),
        ignore_index=True, )
    .rename(columns=str.lower)
    .rename(
        columns={
            'sector1time': 'sector1',
            'sector2time': 'sector2',
            'sector3time': 'sector3',
        }
    )
    .query('laptime < 500 or laptime.isna()')
    .assign(
        full_name=lambda df: df['driver'].apply(lambda x: drivers_map[x][0]),
        team=lambda df: df['driver'].apply(lambda x: drivers_map[x][1]),
    )
)

f1_team

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
0,NOR,1.0,1.0,100.424,NaN,41.379,27.852,186.0,MEDIUM,Singapore,Lando Norris,McLaren
1,NOR,2.0,1.0,98.480,29.268,41.412,27.800,276.0,MEDIUM,Singapore,Lando Norris,McLaren
2,NOR,3.0,1.0,98.406,29.354,41.262,27.790,270.0,MEDIUM,Singapore,Lando Norris,McLaren
3,NOR,4.0,1.0,98.446,29.399,41.305,27.742,272.0,MEDIUM,Singapore,Lando Norris,McLaren
4,NOR,5.0,1.0,97.938,29.034,41.159,27.745,278.0,MEDIUM,Singapore,Lando Norris,McLaren
...,...,...,...,...,...,...,...,...,...,...,...,...
26829,RUS,30.0,4.0,101.237,31.859,41.018,28.360,300.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26830,RUS,31.0,4.0,101.902,31.950,41.210,28.742,299.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26831,RUS,32.0,4.0,103.085,32.488,41.387,29.210,290.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26832,RUS,33.0,4.0,106.221,32.329,41.835,32.057,262.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26833,GAS,1.0,1.0,NaN,NaN,NaN,NaN,NaN,MEDIUM,Great Britain,Pierre Gasly,Alpine

In [4]:
(
    f1_team.query('full_name == "Max Verstappen"')
    .groupby('track')
    .agg(
        position=('position', 'last')
    )
    .reset_index()
)

             track  position
0        Abu Dhabi       6.0
1           Austin       4.0
2        Australia      19.0
3          Austria       5.0
4       Azerbaijan       5.0
5          Barhain       1.0
6          Belgium       5.0
7           Brazil       1.0
8           Canada       1.0
9            China       1.0
10  Emilia Romagna       1.0
11   Great Britain       2.0
12         Hungary       5.0
13           Italy       6.0
14           Japan       1.0
15       Las Vegas       5.0
16          Mexico       6.0
17           Miami       2.0
18          Monaco       6.0
19      Netherland       2.0
20           Qatar       1.0
21    Saudi Arabia       1.0
22       Singapore       2.0
23           Spain       1.0

In [5]:
(
    f1_team.query('full_name == "Max Verstappen"')
    .groupby('track')
    .agg(
        best_lap=('laptime', 'min')
    )
    .reset_index()
)

             track  best_lap
0        Abu Dhabi    87.765
1           Austin    98.117
2        Australia    83.115
3          Austria    67.719
4       Azerbaijan   106.798
5          Barhain    92.608
6          Belgium   106.128
7           Brazil    80.472
8           Canada    75.569
9            China    98.406
10  Emilia Romagna    80.366
11   Great Britain    88.952
12         Hungary    80.908
13           Italy    81.745
14           Japan    93.706
15       Las Vegas    96.248
16          Mexico    80.872
17           Miami    91.261
18          Monaco    74.569
19      Netherland    74.752
20           Qatar    82.905
21    Saudi Arabia    92.608
22       Singapore    95.967
23           Spain    77.776

In [6]:
(
    pd.concat(
        ((pd.read_csv(x)
        .assign(
            track=x.split('/')[1].split('2')[0].replace('_', ' ')
        ) for x in glob('data/*.csv'))),
        ignore_index=True, )
    .rename(columns=str.lower)
    .rename(
        columns={
            'sector1time': 'sector1',
            'sector2time': 'sector2',
            'sector3time': 'sector3',
        }
    )
    .assign(
        full_name=lambda df: df['driver'].apply(lambda x: drivers_map[x][0]),
        team=lambda df: df['driver'].apply(lambda x: drivers_map[x][1]),
    )
)

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
0,NOR,1.0,1.0,100.424,NaN,41.379,27.852,186.0,MEDIUM,Singapore,Lando Norris,McLaren
1,NOR,2.0,1.0,98.480,29.268,41.412,27.800,276.0,MEDIUM,Singapore,Lando Norris,McLaren
2,NOR,3.0,1.0,98.406,29.354,41.262,27.790,270.0,MEDIUM,Singapore,Lando Norris,McLaren
3,NOR,4.0,1.0,98.446,29.399,41.305,27.742,272.0,MEDIUM,Singapore,Lando Norris,McLaren
4,NOR,5.0,1.0,97.938,29.034,41.159,27.745,278.0,MEDIUM,Singapore,Lando Norris,McLaren
...,...,...,...,...,...,...,...,...,...,...,...,...
26829,RUS,30.0,4.0,101.237,31.859,41.018,28.360,300.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26830,RUS,31.0,4.0,101.902,31.950,41.210,28.742,299.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26831,RUS,32.0,4.0,103.085,32.488,41.387,29.210,290.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26832,RUS,33.0,4.0,106.221,32.329,41.835,32.057,262.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26833,GAS,1.0,1.0,NaN,NaN,NaN,NaN,NaN,MEDIUM,Great Britain,Pierre Gasly,Alpine

In [7]:
f1_team.query('track == "Austin" and full_name == "Lewis Hamilton"')

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
2011,HAM,1.0,12.0,108.064,NaN,42.336,34.43,317.0,HARD,Austin,Lewis Hamilton,Mercedes
2012,HAM,2.0,NaN,NaN,NaN,NaN,NaN,NaN,HARD,Austin,Lewis Hamilton,Mercedes

In [8]:
f1_team.loc[f1_team.groupby('track')['maxspeed'].idxmax()]

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
7801,PIA,38.0,14.0,88.238,17.672,37.733,32.833,341.0,HARD,Abu Dhabi,Oscar Piastri,McLaren
2077,RUS,9.0,16.0,101.913,27.220,40.168,34.525,344.0,HARD,Austin,George Russel,Mercedes
25437,HUL,41.0,10.0,82.016,28.708,17.905,35.403,326.0,HARD,Australia,Nico Hulkenberg,Haas
13559,HUL,2.0,8.0,70.217,17.533,31.155,21.529,325.0,MEDIUM,Austria,Nico Hulkenberg,Haas
2919,HAM,15.0,17.0,108.754,39.163,44.460,25.131,334.0,HARD,Azerbaijan,Lewis Hamilton,Mercedes
9087,SAI,17.0,4.0,95.507,30.202,41.758,23.547,332.0,HARD,Barhain,Carlos Sainz,Ferrari
24417,OCO,32.0,13.0,106.992,30.450,47.965,28.577,325.0,HARD,Belgium,Esteban Ocon,Alpine
8157,LEC,60.0,5.0,81.631,20.831,43.002,17.798,294.0,INTERMEDIATE,Brazil,Charles Leclerc,Ferrari
12397,MAG,70.0,12.0,77.110,22.203,24.468,30.439,347.0,MEDIUM,Canada,Kevin Magnussen,Haas
22185,STR,33.0,17.0,102.201,27.202,31.065,43.934,347.0,MEDIUM,China,Lance Stroll,Aston Martin
21386,MAG,61.0,13.0,81.750,25.626,28.748,27.376,304.0,HARD,Emilia Romagna,Kevin Magnussen,Haas
26716,PER,17.0,15.0,94.829,29.675,38.196,26.958,335.0,HARD,Great Britain,Sergio Perez,Red Bull
4983,RUS,70.0,8.0,84.063,29.633,30.728,23.702,316.0,HARD,Hungary,George Russel,Mercedes
6266,MAG,11.0,11.0,86.040,27.934,29.461,28.645,357.0,MEDIUM,Italy,Kevin Magnussen,Haas
11597,HUL,45.0,14.0,96.808,35.284,42.978,18.546,309.0,HARD,Japan,Nico Hulkenberg,Haas
10151,HAM,16.0,6.0,97.091,27.837,32.943,36.311,350.0,HARD,Las Vegas,Lewis Hamilton,Mercedes
3715,PIA,10.0,16.0,82.793,28.506,32.764,21.523,362.0,MEDIUM,Mexico,Oscar Piastri,McLaren
18606,STR,35.0,17.0,92.950,31.857,35.423,25.670,355.0,MEDIUM,Miami,Lance Stroll,Aston Martin
19943,HAM,78.0,7.0,76.355,19.818,35.947,20.590,289.0,HARD,Monaco,Lewis Hamilton,Mercedes
14942,SAI,47.0,6.0,75.105,25.329,27.337,22.439,335.0,HARD,Netherland,Carlos Sainz,Ferrari
18057,HAM,56.0,12.0,84.412,31.396,28.447,24.569,336.0,HARD,Qatar,Lewis Hamilton,Mercedes
23035,SAI,17.0,4.0,95.507,30.202,41.758,23.547,332.0,HARD,Saudi Arabia,Carlos Sainz,Ferrari
647,COL,31.0,12.0,100.451,30.385,42.358,27.708,305.0,HARD,Singapore,Franco Colapinto,Williams
17089,MAG,5.0,16.0,83.042,23.714,34.392,24.936,343.0,SOFT,Spain,Kevin Magnussen,Haas

In [9]:
f1_team.query("track == 'Great Britain'").groupby('full_name').agg(max_speed=('maxspeed', 'max'))

                  max_speed
full_name
Alexander Albon       331.0
Carlos Sainz          322.0
Charles Leclerc       328.0
Daniel Ricciardo      327.0
Esteban Ocon          332.0
Fernando Alonso       332.0
George Russel         309.0
Kevin Magnussen       334.0
Lance Stroll          328.0
Lando Norris          326.0
Lewis Hamilton        319.0
Logan Sargeant        329.0
Max Verstappen        327.0
Nico Hulkenberg       325.0
Oscar Piastri         329.0
Pierre Gasly            NaN
Sergio Perez          335.0
Valtteri Bottas       322.0
Yuki Tsunoda          333.0
Zhou Guanyu           329.0

In [10]:
testName = "Max Verstappen"
testTrack = "Belgium"

In [11]:
(
    f1_team
    .query(f"full_name == '{testName}' and track == '{testTrack}'")
)

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
24166,VER,1.0,9.0,117.183,NaN,52.573,29.298,300.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24167,VER,2.0,8.0,109.828,30.820,49.592,29.416,315.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24168,VER,3.0,8.0,110.141,30.975,49.693,29.473,307.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24169,VER,4.0,8.0,110.055,31.020,49.636,29.399,306.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24170,VER,5.0,8.0,110.138,31.118,49.599,29.421,308.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24171,VER,6.0,8.0,110.073,30.920,49.795,29.358,309.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24172,VER,7.0,8.0,110.146,31.044,49.700,29.402,307.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24173,VER,8.0,8.0,110.094,30.957,49.759,29.378,309.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24174,VER,9.0,8.0,110.609,30.938,50.214,29.457,310.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24175,VER,10.0,8.0,114.655,31.005,49.825,33.825,308.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24176,VER,11.0,13.0,122.789,45.573,48.109,29.107,310.0,HARD,Belgium,Max Verstappen,Red Bull
24177,VER,12.0,10.0,108.403,30.615,48.559,29.229,315.0,HARD,Belgium,Max Verstappen,Red Bull
24178,VER,13.0,9.0,108.431,31.082,48.239,29.110,312.0,HARD,Belgium,Max Verstappen,Red Bull
24179,VER,14.0,8.0,108.153,30.851,48.222,29.080,NaN,HARD,Belgium,Max Verstappen,Red Bull
24180,VER,15.0,8.0,108.229,30.811,48.342,29.076,313.0,HARD,Belgium,Max Verstappen,Red Bull
24181,VER,16.0,7.0,108.509,30.808,48.571,29.130,315.0,HARD,Belgium,Max Verstappen,Red Bull
24182,VER,17.0,7.0,108.431,30.753,48.584,29.094,311.0,HARD,Belgium,Max Verstappen,Red Bull
24183,VER,18.0,7.0,108.896,30.775,48.975,29.146,313.0,HARD,Belgium,Max Verstappen,Red Bull
24184,VER,19.0,7.0,108.578,30.879,48.583,29.116,314.0,HARD,Belgium,Max Verstappen,Red Bull
24185,VER,20.0,7.0,109.134,30.947,48.912,29.275,311.0,HARD,Belgium,Max Verstappen,Red Bull
24186,VER,21.0,5.0,109.273,30.823,49.246,29.204,314.0,HARD,Belgium,Max Verstappen,Red Bull
24187,VER,22.0,5.0,108.448,31.091,48.204,29.153,313.0,HARD,Belgium,Max Verstappen,Red Bull
24188,VER,23.0,5.0,108.494,31.211,48.197,29.086,312.0,HARD,Belgium,Max Verstappen,Red Bull
24189,VER,24.0,5.0,108.154,31.173,48.096,28.885,313.0,HARD,Belgium,Max Verstappen,Red Bull
24190,VER,25.0,5.0,107.921,31.127,47.886,28.908,314.0,HARD,Belgium,Max Verstappen,Red Bull
24191,VER,26.0,4.0,107.815,31.124,47.815,28.876,NaN,HARD,Belgium,Max Verstappen,Red Bull
24192,VER,27.0,3.0,107.431,31.032,47.549,28.850,315.0,HARD,Belgium,Max Verstappen,Red Bull
24193,VER,28.0,4.0,112.026,31.021,47.724,33.281,NaN,HARD,Belgium,Max Verstappen,Red Bull
24194,VER,29.0,7.0,120.489,45.265,46.585,28.639,311.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24195,VER,30.0,5.0,106.447,30.611,47.026,28.810,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24196,VER,31.0,5.0,106.363,30.950,46.698,28.715,310.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24197,VER,32.0,5.0,106.128,30.875,46.512,28.741,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24198,VER,33.0,5.0,106.417,30.904,46.670,28.843,314.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24199,VER,34.0,5.0,106.630,30.957,46.821,28.852,315.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24200,VER,35.0,5.0,107.009,30.947,47.264,28.798,314.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24201,VER,36.0,5.0,107.156,30.906,47.253,28.997,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24202,VER,37.0,5.0,107.200,30.765,47.596,28.839,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24203,VER,38.0,5.0,107.177,30.850,47.473,28.854,317.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24204,VER,39.0,5.0,107.244,30.883,47.479,28.882,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24205,VER,40.0,5.0,107.227,30.646,47.673,28.908,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24206,VER,41.0,5.0,107.354,30.598,47.920,28.836,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24207,VER,42.0,5.0,107.387,30.637,47.949,28.801,319.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24208,VER,43.0,5.0,107.102,30.579,47.831,28.692,317.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24209,VER,44.0,5.0,106.899,30.605,47.569,28.725,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull

In [12]:
(
    f1_team
    .query(f"track == '{testTrack}' and lapnumber == 14")["sector1"]
)

24047    31.323
24091    31.012
24135    31.152
24179    30.851
24223    31.359
24267    31.439
24311    30.765
24355    45.406
24399    30.471
24443    31.368
24487    31.040
24531    31.156
24575    31.043
24619    31.505
24663    30.670
24707    31.394
24751    31.194
24795    30.541
24844    30.840
Name: sector1, dtype: float64

In [13]:
updated = (
    f1_team
    .query(f"full_name == '{testName}' and track == '{testTrack}'")
)

for key, value in updated.items():
    print(f"{key}: {value.values[0]}")

updated

driver: VER
lapnumber: 1.0
position: 9.0
laptime: 117.183
sector1: nan
sector2: 52.573
sector3: 29.298
maxspeed: 300.0
compound: MEDIUM
track: Belgium
full_name: Max Verstappen
team: Red Bull

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
24166,VER,1.0,9.0,117.183,NaN,52.573,29.298,300.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24167,VER,2.0,8.0,109.828,30.820,49.592,29.416,315.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24168,VER,3.0,8.0,110.141,30.975,49.693,29.473,307.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24169,VER,4.0,8.0,110.055,31.020,49.636,29.399,306.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24170,VER,5.0,8.0,110.138,31.118,49.599,29.421,308.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24171,VER,6.0,8.0,110.073,30.920,49.795,29.358,309.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24172,VER,7.0,8.0,110.146,31.044,49.700,29.402,307.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24173,VER,8.0,8.0,110.094,30.957,49.759,29.378,309.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24174,VER,9.0,8.0,110.609,30.938,50.214,29.457,310.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24175,VER,10.0,8.0,114.655,31.005,49.825,33.825,308.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24176,VER,11.0,13.0,122.789,45.573,48.109,29.107,310.0,HARD,Belgium,Max Verstappen,Red Bull
24177,VER,12.0,10.0,108.403,30.615,48.559,29.229,315.0,HARD,Belgium,Max Verstappen,Red Bull
24178,VER,13.0,9.0,108.431,31.082,48.239,29.110,312.0,HARD,Belgium,Max Verstappen,Red Bull
24179,VER,14.0,8.0,108.153,30.851,48.222,29.080,NaN,HARD,Belgium,Max Verstappen,Red Bull
24180,VER,15.0,8.0,108.229,30.811,48.342,29.076,313.0,HARD,Belgium,Max Verstappen,Red Bull
24181,VER,16.0,7.0,108.509,30.808,48.571,29.130,315.0,HARD,Belgium,Max Verstappen,Red Bull
24182,VER,17.0,7.0,108.431,30.753,48.584,29.094,311.0,HARD,Belgium,Max Verstappen,Red Bull
24183,VER,18.0,7.0,108.896,30.775,48.975,29.146,313.0,HARD,Belgium,Max Verstappen,Red Bull
24184,VER,19.0,7.0,108.578,30.879,48.583,29.116,314.0,HARD,Belgium,Max Verstappen,Red Bull
24185,VER,20.0,7.0,109.134,30.947,48.912,29.275,311.0,HARD,Belgium,Max Verstappen,Red Bull
24186,VER,21.0,5.0,109.273,30.823,49.246,29.204,314.0,HARD,Belgium,Max Verstappen,Red Bull
24187,VER,22.0,5.0,108.448,31.091,48.204,29.153,313.0,HARD,Belgium,Max Verstappen,Red Bull
24188,VER,23.0,5.0,108.494,31.211,48.197,29.086,312.0,HARD,Belgium,Max Verstappen,Red Bull
24189,VER,24.0,5.0,108.154,31.173,48.096,28.885,313.0,HARD,Belgium,Max Verstappen,Red Bull
24190,VER,25.0,5.0,107.921,31.127,47.886,28.908,314.0,HARD,Belgium,Max Verstappen,Red Bull
24191,VER,26.0,4.0,107.815,31.124,47.815,28.876,NaN,HARD,Belgium,Max Verstappen,Red Bull
24192,VER,27.0,3.0,107.431,31.032,47.549,28.850,315.0,HARD,Belgium,Max Verstappen,Red Bull
24193,VER,28.0,4.0,112.026,31.021,47.724,33.281,NaN,HARD,Belgium,Max Verstappen,Red Bull
24194,VER,29.0,7.0,120.489,45.265,46.585,28.639,311.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24195,VER,30.0,5.0,106.447,30.611,47.026,28.810,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24196,VER,31.0,5.0,106.363,30.950,46.698,28.715,310.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24197,VER,32.0,5.0,106.128,30.875,46.512,28.741,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24198,VER,33.0,5.0,106.417,30.904,46.670,28.843,314.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24199,VER,34.0,5.0,106.630,30.957,46.821,28.852,315.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24200,VER,35.0,5.0,107.009,30.947,47.264,28.798,314.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24201,VER,36.0,5.0,107.156,30.906,47.253,28.997,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24202,VER,37.0,5.0,107.200,30.765,47.596,28.839,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24203,VER,38.0,5.0,107.177,30.850,47.473,28.854,317.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24204,VER,39.0,5.0,107.244,30.883,47.479,28.882,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24205,VER,40.0,5.0,107.227,30.646,47.673,28.908,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24206,VER,41.0,5.0,107.354,30.598,47.920,28.836,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24207,VER,42.0,5.0,107.387,30.637,47.949,28.801,319.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24208,VER,43.0,5.0,107.102,30.579,47.831,28.692,317.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24209,VER,44.0,5.0,106.899,30.605,47.569,28.725,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull

In [14]:
float(updated.query('lapnumber == 5')['sector1'].values[0])

31.118

In [15]:
def get_best_time_on_sector(track, lap, sector):
    return float(f1_team.query(f"track == '{track}' and lapnumber == {lap}")[sector].min())

In [16]:
get_best_time_on_sector('Belgium', 14, 'sector1')

30.471

In [17]:
name, track = 'Max Verstappen', 'Singapore'

In [18]:
updated = (
    f1_team
    .query(f"full_name == '{name}' and track == '{track}'")
)
updated['sector1_color'] = 'green'
updated['sector2_color'] = 'blue'
updated['sector3_color'] = 'red'

best_lap = [500, 500, 500]
for lap in range(1, len(updated) + 1):
    i = 0
    for sector in ['sector1', 'sector2', 'sector3']:
        current = updated.query(f"lapnumber == {lap}")
        if current.empty:
            continue
        time = float(current[sector].values[0])
        if time < best_lap[i]:
            if time <= get_best_time_on_sector(track, lap, sector):
                updated.loc[current.index, f"{sector}_color"] = 'purple'
            else:
                updated.loc[current.index, f"{sector}_color"] = 'green'
            best_lap[i] = time
        else:
            updated.loc[current.index, f"{sector}_color"] = 'red'
        if sector == 'sector2':
            print(best_lap[i], time, get_best_time_on_sector(track, lap, sector))
        i += 1
updated

41.689 41.689 41.379
41.689 41.805 41.412
41.641 41.641 41.262
41.518 41.518 41.305
41.31 41.31 41.159
41.31 41.383 41.224
41.271 41.271 41.128
41.083 41.083 40.798
41.083 41.421 40.658
41.083 41.405 40.859
41.083 41.269 40.842
41.083 41.425 40.831
41.083 41.182 40.666
41.083 41.292 40.542
41.083 41.348 40.737
41.083 41.338 40.93
41.083 41.423 40.959
41.083 41.611 41.085
41.083 41.483 41.2
41.083 41.569 41.172
41.083 41.72 41.088
41.083 41.704 41.272
41.083 41.711 41.138
41.083 41.782 41.386
41.083 41.99 41.373
41.083 41.818 41.187
41.083 41.975 41.425
41.083 42.261 41.034
41.083 42.515 41.103
41.083 41.662 41.104
40.86 40.86 40.86
40.86 40.928 40.761
40.86 41.013 40.783
40.86 40.998 40.807
40.86 41.14 40.706
40.86 41.062 40.535
40.86 41.058 40.644
40.86 41.074 40.705
40.86 41.115 40.716
40.86 41.048 41.038
40.86 41.247 40.762
40.86 41.058 40.724
40.814 40.814 40.571
40.752 40.752 40.386
40.752 40.993 40.586
40.752 40.938 40.369
40.752 40.908 40.515
40.752 40.922 40.206
40.752 40.909 40.596
40.752 41.192 40.749
40.752 41.295 40.058
40.752 41.176 40.652
40.752 41.069 40.695
40.752 40.957 40.947
40.752 40.901 40.675
40.752 40.869 40.869
40.752 40.787 40.787
40.749 40.749 40.719
40.694 40.694 40.694
40.694 40.793 39.948
40.694 40.738 40.738
40.694 40.974 40.974

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team,sector1_color,sector2_color,sector3_color
62,VER,1.0,2.0,101.413,NaN,41.689,27.888,189.0,MEDIUM,Singapore,Max Verstappen,Red Bull,red,green,green
63,VER,2.0,2.0,98.790,29.027,41.805,27.958,276.0,MEDIUM,Singapore,Max Verstappen,Red Bull,green,red,red
64,VER,3.0,2.0,98.917,29.353,41.641,27.923,274.0,MEDIUM,Singapore,Max Verstappen,Red Bull,red,green,red
65,VER,4.0,2.0,98.470,29.193,41.518,27.759,273.0,MEDIUM,Singapore,Max Verstappen,Red Bull,red,green,green
66,VER,5.0,2.0,97.906,29.031,41.310,27.565,275.0,MEDIUM,Singapore,Max Verstappen,Red Bull,red,green,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,VER,58.0,2.0,96.171,28.499,40.749,26.923,279.0,HARD,Singapore,Max Verstappen,Red Bull,green,green,red
120,VER,59.0,2.0,95.967,28.352,40.694,26.921,281.0,HARD,Singapore,Max Verstappen,Red Bull,purple,purple,red
121,VER,60.0,2.0,96.343,28.536,40.793,27.014,NaN,HARD,Singapore,Max Verstappen,Red Bull,red,red,red
122,VER,61.0,2.0,96.013,28.446,40.738,26.829,NaN,HARD,Singapore,Max Verstappen,Red Bull,red,red,purple
123,VER,62.0,2.0,96.931,28.636,40.974,27.321,NaN,HARD,Singapore,Max Verstappen,Red Bull,red,red,red

In [19]:
f1_team.query('track == "Australia" and driver == "VER"')

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
24875,VER,1.0,1.0,87.458,NaN,18.462,35.518,238.0,MEDIUM,Australia,Max Verstappen,Red Bull
24876,VER,2.0,2.0,84.099,29.623,18.375,36.101,281.0,MEDIUM,Australia,Max Verstappen,Red Bull
24877,VER,3.0,2.0,83.115,28.793,18.573,35.749,305.0,MEDIUM,Australia,Max Verstappen,Red Bull
24878,VER,4.0,19.0,NaN,28.756,18.353,NaN,302.0,MEDIUM,Australia,Max Verstappen,Red Bull

In [20]:
(
    f1_team
    .query(f'full_name == "{name}"')
    .groupby('track')
    .agg(
        position=('position', 'last')
    )
    .reset_index()
)

             track  position
0        Abu Dhabi       6.0
1           Austin       4.0
2        Australia      19.0
3          Austria       5.0
4       Azerbaijan       5.0
5          Barhain       1.0
6          Belgium       5.0
7           Brazil       1.0
8           Canada       1.0
9            China       1.0
10  Emilia Romagna       1.0
11   Great Britain       2.0
12         Hungary       5.0
13           Italy       6.0
14           Japan       1.0
15       Las Vegas       5.0
16          Mexico       6.0
17           Miami       2.0
18          Monaco       6.0
19      Netherland       2.0
20           Qatar       1.0
21    Saudi Arabia       1.0
22       Singapore       2.0
23           Spain       1.0

In [21]:
updated = (
    f1_team
    .query(f"full_name == '{name}' and track == '{track}'")
)
updated['sector1_color'] = 'green'
updated['sector2_color'] = 'blue'
updated['sector3_color'] = 'red'

best_lap = [500, 500, 500]
laps_count = updated['lapnumber'].max()
for lap in range(1, int(laps_count) + 1):
    i = 0
    for sector in ['sector1', 'sector2', 'sector3']:
        current = updated.query(f"lapnumber == {lap}")
        if current.empty:
            i += 1
            continue
        time = float(current[sector].values[0])
        if time < best_lap[i]:
            if time <= get_best_time_on_sector(track, lap, sector):
                updated.loc[current.index, f"{sector}_color"] = 'purple'
            else:
                updated.loc[current.index, f"{sector}_color"] = 'green'
            best_lap[i] = time
        else:
            updated.loc[current.index, f"{sector}_color"] = 'red'
        updated.loc[current.index, f"{sector}_best"] = get_best_time_on_sector(track, lap, sector)
        updated.loc[current.index, f"{sector}_personal_best"] = best_lap[i]
        i += 1

updated

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,...,team,sector1_color,sector2_color,sector3_color,sector1_best,sector1_personal_best,sector2_best,sector2_personal_best,sector3_best,sector3_personal_best
62,VER,1.0,2.0,101.413,NaN,41.689,27.888,189.0,MEDIUM,Singapore,...,Red Bull,red,green,green,NaN,500.000,41.379,41.689,27.790,27.888
63,VER,2.0,2.0,98.790,29.027,41.805,27.958,276.0,MEDIUM,Singapore,...,Red Bull,green,red,red,28.986,29.027,41.412,41.689,27.654,27.888
64,VER,3.0,2.0,98.917,29.353,41.641,27.923,274.0,MEDIUM,Singapore,...,Red Bull,red,green,red,28.921,29.027,41.262,41.641,27.753,27.888
65,VER,4.0,2.0,98.470,29.193,41.518,27.759,273.0,MEDIUM,Singapore,...,Red Bull,red,green,green,28.870,29.027,41.305,41.518,27.611,27.759
66,VER,5.0,2.0,97.906,29.031,41.310,27.565,275.0,MEDIUM,Singapore,...,Red Bull,red,green,green,28.708,29.027,41.159,41.310,27.531,27.565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,VER,58.0,2.0,96.171,28.499,40.749,26.923,279.0,HARD,Singapore,...,Red Bull,green,green,red,28.433,28.499,40.719,40.749,26.895,26.907
120,VER,59.0,2.0,95.967,28.352,40.694,26.921,281.0,HARD,Singapore,...,Red Bull,purple,purple,red,28.352,28.352,40.694,40.694,26.921,26.907
121,VER,60.0,2.0,96.343,28.536,40.793,27.014,NaN,HARD,Singapore,...,Red Bull,red,red,red,28.091,28.352,39.948,40.694,26.447,26.907
122,VER,61.0,2.0,96.013,28.446,40.738,26.829,NaN,HARD,Singapore,...,Red Bull,red,red,purple,28.446,28.352,40.738,40.694,26.829,26.829
123,VER,62.0,2.0,96.931,28.636,40.974,27.321,NaN,HARD,Singapore,...,Red Bull,red,red,red,28.415,28.352,40.974,40.694,27.093,26.829

In [22]:
updated['sector1_best']

62        NaN
63     28.986
64     28.921
65     28.870
66     28.708
        ...
119    28.433
120    28.352
121    28.091
122    28.446
123    28.415
Name: sector1_best, Length: 62, dtype: float64

In [23]:
(
    f1_team
    .query(f"track == '{track}'")
    .groupby('full_name')
    .agg(
        position=('position', 'last'),
    )
    .reset_index()
    .sort_values('position')
)

           full_name  position
10      Lando Norris       1.0
12    Max Verstappen       2.0
14     Oscar Piastri       3.0
7      George Russel       4.0
2    Charles Leclerc       5.0
11    Lewis Hamilton       6.0
1       Carlos Sainz       7.0
5    Fernando Alonso       8.0
13   Nico Hulkenberg       9.0
16      Sergio Perez      10.0
6   Franco Colapinto      11.0
18      Yuki Tsunoda      12.0
4       Esteban Ocon      13.0
9       Lance Stroll      14.0
19       Zhou Guanyu      15.0
17   Valtteri Bottas      16.0
15      Pierre Gasly      17.0
3   Daniel Ricciardo      18.0
8    Kevin Magnussen      19.0
0    Alexander Albon      20.0

In [24]:
(
    f1_team
    .query(f"track == '{track}'")
    .groupby('full_name')
    .agg(
        max_lap=('lapnumber', 'max'),
    )
    .reset_index()
)['max_lap'].max()

np.float64(62.0)

In [25]:
lap = 14
(
    f1_team
    .query(f"track == '{track}' and full_name == 'Alexander Albon'")
)

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
1162,ALB,1.0,15.0,110.771,NaN,45.094,28.543,223.0,MEDIUM,Singapore,Alexander Albon,Williams
1163,ALB,2.0,15.0,100.750,29.598,42.998,28.154,281.0,MEDIUM,Singapore,Alexander Albon,Williams
1164,ALB,3.0,15.0,99.762,29.259,42.539,27.964,285.0,MEDIUM,Singapore,Alexander Albon,Williams
1165,ALB,4.0,15.0,99.285,29.108,42.303,27.874,281.0,MEDIUM,Singapore,Alexander Albon,Williams
1166,ALB,5.0,15.0,99.252,29.368,42.028,27.856,293.0,MEDIUM,Singapore,Alexander Albon,Williams
1167,ALB,6.0,15.0,99.267,29.047,42.338,27.882,286.0,MEDIUM,Singapore,Alexander Albon,Williams
1168,ALB,7.0,15.0,99.039,29.115,42.037,27.887,296.0,MEDIUM,Singapore,Alexander Albon,Williams
1169,ALB,8.0,15.0,99.316,28.937,42.166,28.213,295.0,MEDIUM,Singapore,Alexander Albon,Williams
1170,ALB,9.0,15.0,99.767,29.275,42.130,28.362,289.0,MEDIUM,Singapore,Alexander Albon,Williams
1171,ALB,10.0,15.0,99.896,29.241,42.267,28.388,291.0,MEDIUM,Singapore,Alexander Albon,Williams
1172,ALB,11.0,17.0,106.666,29.101,42.374,35.191,275.0,MEDIUM,Singapore,Alexander Albon,Williams
1173,ALB,12.0,19.0,118.026,49.705,40.831,27.490,NaN,HARD,Singapore,Alexander Albon,Williams
1174,ALB,13.0,19.0,96.888,28.928,40.666,27.294,274.0,HARD,Singapore,Alexander Albon,Williams
1175,ALB,14.0,19.0,98.740,29.358,41.648,27.734,278.0,HARD,Singapore,Alexander Albon,Williams
1176,ALB,15.0,20.0,133.278,35.672,54.488,43.118,274.0,HARD,Singapore,Alexander Albon,Williams

In [26]:
(
    f1_team
    .query(f"track == '{track}'")
    .groupby('lapnumber')
    .agg(
        best_sector1=('sector1', 'min'),
        best_sector2=('sector2', 'min'),
        best_sector3=('sector3', 'min'),
    )
    .reset_index()
)

    lapnumber  best_sector1  best_sector2  best_sector3
0         1.0           NaN        41.379        27.790
1         2.0        28.986        41.412        27.654
2         3.0        28.921        41.262        27.753
3         4.0        28.870        41.305        27.611
4         5.0        28.708        41.159        27.531
..        ...           ...           ...           ...
57       58.0        28.433        40.719        26.895
58       59.0        28.352        40.694        26.921
59       60.0        28.091        39.948        26.447
60       61.0        28.446        40.738        26.829
61       62.0        28.415        40.974        27.093

[62 rows x 4 columns]

In [27]:
(
    f1_team
    .query(f"track == '{track}' and lapnumber == 62")
    .groupby('compound')
    .size()
    .reset_index(name='count')
)

  compound  count
0     HARD      7

In [28]:
(
    f1_team
    .query(f"track == '{track}'")
    .groupby('full_name')
    .agg(
        maxspeed=('maxspeed', 'max')
    )
    .reset_index()
)

           full_name  maxspeed
0    Alexander Albon     296.0
1       Carlos Sainz     298.0
2    Charles Leclerc     302.0
3   Daniel Ricciardo     294.0
4       Esteban Ocon     297.0
5    Fernando Alonso     302.0
6   Franco Colapinto     305.0
7      George Russel     301.0
8    Kevin Magnussen     303.0
9       Lance Stroll     302.0
10      Lando Norris     290.0
11    Lewis Hamilton     298.0
12    Max Verstappen     294.0
13   Nico Hulkenberg     295.0
14     Oscar Piastri     300.0
15      Pierre Gasly     301.0
16      Sergio Perez     300.0
17   Valtteri Bottas     299.0
18      Yuki Tsunoda     295.0
19       Zhou Guanyu     295.0

In [29]:
(
    f1_team
    .query(f"track == '{track}' and lapnumber == 15")
)

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
14,NOR,15.0,1.0,96.758,28.747,40.861,27.150,282.0,MEDIUM,Singapore,Lando Norris,McLaren
76,VER,15.0,2.0,97.826,28.967,41.348,27.511,277.0,MEDIUM,Singapore,Max Verstappen,Red Bull
138,PIA,15.0,5.0,98.435,29.004,41.615,27.816,281.0,MEDIUM,Singapore,Oscar Piastri,McLaren
200,RUS,15.0,4.0,98.459,29.215,41.752,27.492,280.0,MEDIUM,Singapore,George Russel,Mercedes
262,LEC,15.0,8.0,98.515,28.669,42.226,27.620,285.0,MEDIUM,Singapore,Charles Leclerc,Ferrari
324,HAM,15.0,3.0,98.287,29.157,41.711,27.419,279.0,SOFT,Singapore,Lewis Hamilton,Mercedes
386,SAI,15.0,18.0,96.561,28.711,40.737,27.113,279.0,HARD,Singapore,Carlos Sainz,Ferrari
448,ALO,15.0,7.0,99.008,28.966,42.135,27.907,NaN,MEDIUM,Singapore,Fernando Alonso,Aston Martin
509,HUL,15.0,6.0,98.799,29.181,41.921,27.697,283.0,MEDIUM,Singapore,Nico Hulkenberg,Haas
570,PER,15.0,10.0,99.102,29.277,41.938,27.887,281.0,MEDIUM,Singapore,Sergio Perez,Red Bull
631,COL,15.0,9.0,98.858,29.288,41.770,27.800,280.0,MEDIUM,Singapore,Franco Colapinto,Williams
692,TSU,15.0,11.0,99.349,29.336,42.166,27.847,NaN,MEDIUM,Singapore,Yuki Tsunoda,Racing Bulls
753,OCO,15.0,12.0,99.276,29.307,42.206,27.763,281.0,MEDIUM,Singapore,Esteban Ocon,Alpine
814,STR,15.0,15.0,99.494,29.276,42.253,27.965,NaN,HARD,Singapore,Lance Stroll,Aston Martin
875,ZHO,15.0,16.0,99.610,29.388,42.311,27.911,282.0,HARD,Singapore,Zhou Guanyu,Kick Sauber
936,BOT,15.0,17.0,99.404,29.361,42.080,27.963,279.0,HARD,Singapore,Valtteri Bottas,Kick Sauber
997,GAS,15.0,14.0,99.491,29.460,42.232,27.799,NaN,MEDIUM,Singapore,Pierre Gasly,Alpine
1058,RIC,15.0,19.0,98.774,29.170,41.953,27.651,276.0,MEDIUM,Singapore,Daniel Ricciardo,Racing Bulls
1119,MAG,15.0,13.0,99.385,29.214,42.401,27.770,286.0,HARD,Singapore,Kevin Magnussen,Haas
1176,ALB,15.0,20.0,133.278,35.672,54.488,43.118,274.0,HARD,Singapore,Alexander Albon,Williams

In [30]:
last = (
    f1_team
    .sort_values(['track', 'driver', 'lapnumber'])
    .groupby(['track', 'driver'], as_index=False)
    .tail(1)
)

wins = last[last['position'] == 1]

wins_by_driver = (
    wins.groupby("full_name")
    .size()
    .reset_index(name="victories")
    .sort_values("victories", ascending=False)
)

best = wins_by_driver.iloc[0]

" ".join(wins.query("full_name == 'Max Verstappen'")['track'].values)

'Barhain Brazil Canada China Emilia Romagna Japan Qatar Saudi Arabia Spain'

In [31]:
f1_team

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
0,NOR,1.0,1.0,100.424,NaN,41.379,27.852,186.0,MEDIUM,Singapore,Lando Norris,McLaren
1,NOR,2.0,1.0,98.480,29.268,41.412,27.800,276.0,MEDIUM,Singapore,Lando Norris,McLaren
2,NOR,3.0,1.0,98.406,29.354,41.262,27.790,270.0,MEDIUM,Singapore,Lando Norris,McLaren
3,NOR,4.0,1.0,98.446,29.399,41.305,27.742,272.0,MEDIUM,Singapore,Lando Norris,McLaren
4,NOR,5.0,1.0,97.938,29.034,41.159,27.745,278.0,MEDIUM,Singapore,Lando Norris,McLaren
...,...,...,...,...,...,...,...,...,...,...,...,...
26829,RUS,30.0,4.0,101.237,31.859,41.018,28.360,300.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26830,RUS,31.0,4.0,101.902,31.950,41.210,28.742,299.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26831,RUS,32.0,4.0,103.085,32.488,41.387,29.210,290.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26832,RUS,33.0,4.0,106.221,32.329,41.835,32.057,262.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26833,GAS,1.0,1.0,NaN,NaN,NaN,NaN,NaN,MEDIUM,Great Britain,Pierre Gasly,Alpine

In [32]:
df = (
    f1_team
    .sort_values(['track', 'driver', 'lapnumber'])
    .groupby(['track', 'driver'], as_index=False)
    .tail(1)
)

idx = f1_team.groupby("track")["maxspeed"].idxmax()
fastest_by_track = f1_team.loc[idx, ["track", "full_name", "driver", "maxspeed", "lapnumber"]]
fastest_by_track = fastest_by_track.reset_index().sort_values("maxspeed", ascending=False)

fastest_by_track

    index           track         full_name driver  maxspeed  lapnumber
16   3715          Mexico     Oscar Piastri    PIA     362.0       10.0
13   6266           Italy   Kevin Magnussen    MAG     357.0       11.0
17  18606           Miami      Lance Stroll    STR     355.0       35.0
15  10151       Las Vegas    Lewis Hamilton    HAM     350.0       16.0
9   22185           China      Lance Stroll    STR     347.0       33.0
8   12397          Canada   Kevin Magnussen    MAG     347.0       70.0
1    2077          Austin     George Russel    RUS     344.0        9.0
23  17089           Spain   Kevin Magnussen    MAG     343.0        5.0
0    7801       Abu Dhabi     Oscar Piastri    PIA     341.0       38.0
20  18057           Qatar    Lewis Hamilton    HAM     336.0       56.0
19  14942      Netherland      Carlos Sainz    SAI     335.0       47.0
11  26716   Great Britain      Sergio Perez    PER     335.0       17.0
4    2919      Azerbaijan    Lewis Hamilton    HAM     334.0       15.0
5    9087         Barhain      Carlos Sainz    SAI     332.0       17.0
21  23035    Saudi Arabia      Carlos Sainz    SAI     332.0       17.0
2   25437       Australia   Nico Hulkenberg    HUL     326.0       41.0
3   13559         Austria   Nico Hulkenberg    HUL     325.0        2.0
6   24417         Belgium      Esteban Ocon    OCO     325.0       32.0
12   4983         Hungary     George Russel    RUS     316.0       70.0
14  11597           Japan   Nico Hulkenberg    HUL     309.0       45.0
22    647       Singapore  Franco Colapinto    COL     305.0       31.0
10  21386  Emilia Romagna   Kevin Magnussen    MAG     304.0       61.0
7    8157          Brazil   Charles Leclerc    LEC     294.0       60.0
18  19943          Monaco    Lewis Hamilton    HAM     289.0       78.0

In [33]:
fastest_by_track

    index           track         full_name driver  maxspeed  lapnumber
16   3715          Mexico     Oscar Piastri    PIA     362.0       10.0
13   6266           Italy   Kevin Magnussen    MAG     357.0       11.0
17  18606           Miami      Lance Stroll    STR     355.0       35.0
15  10151       Las Vegas    Lewis Hamilton    HAM     350.0       16.0
9   22185           China      Lance Stroll    STR     347.0       33.0
8   12397          Canada   Kevin Magnussen    MAG     347.0       70.0
1    2077          Austin     George Russel    RUS     344.0        9.0
23  17089           Spain   Kevin Magnussen    MAG     343.0        5.0
0    7801       Abu Dhabi     Oscar Piastri    PIA     341.0       38.0
20  18057           Qatar    Lewis Hamilton    HAM     336.0       56.0
19  14942      Netherland      Carlos Sainz    SAI     335.0       47.0
11  26716   Great Britain      Sergio Perez    PER     335.0       17.0
4    2919      Azerbaijan    Lewis Hamilton    HAM     334.0       15.0
5    9087         Barhain      Carlos Sainz    SAI     332.0       17.0
21  23035    Saudi Arabia      Carlos Sainz    SAI     332.0       17.0
2   25437       Australia   Nico Hulkenberg    HUL     326.0       41.0
3   13559         Austria   Nico Hulkenberg    HUL     325.0        2.0
6   24417         Belgium      Esteban Ocon    OCO     325.0       32.0
12   4983         Hungary     George Russel    RUS     316.0       70.0
14  11597           Japan   Nico Hulkenberg    HUL     309.0       45.0
22    647       Singapore  Franco Colapinto    COL     305.0       31.0
10  21386  Emilia Romagna   Kevin Magnussen    MAG     304.0       61.0
7    8157          Brazil   Charles Leclerc    LEC     294.0       60.0
18  19943          Monaco    Lewis Hamilton    HAM     289.0       78.0

In [34]:
(
    f1_team
    .sort_values(['track', 'driver', 'lapnumber'])
    .groupby(['track', 'driver'], as_index=False)
    .tail(1)
)
print(df['maxspeed'].idxmax())

fastest_race = df.loc[df['maxspeed'].idxmax()]

track_name = fastest_race["track"]
driver_name = fastest_race["full_name"]
max_speed = fastest_race["maxspeed"]

fastest_race

4336

driver                LAW
lapnumber            70.0
position             16.0
laptime            85.016
sector1            28.371
sector2            34.343
sector3            22.302
maxspeed            355.0
compound             SOFT
track              Mexico
full_name     Liam Lawson
team         Racing Bulls
Name: 4336, dtype: object

In [43]:
circuits_coords = {
    'Abu Dhabi': {'lat': 24.4539, 'lon': 54.3530, 'link': 'https://en.wikipedia.org/wiki/Yas_Marina_Circuit'},
    'Austin': {'lat': 30.1328, 'lon': -97.6411, 'link': 'https://en.wikipedia.org/wiki/Circuit_of_the_Americas'},
    'Australia': {'lat': -37.8150, 'lon': 144.9680, 'link': 'https://en.wikipedia.org/wiki/Albert_Park_Circuit'},
    'Austria': {'lat': 47.2127, 'lon': 14.7675, 'link': 'https://en.wikipedia.org/wiki/Red_Bull_Ring'},
    'Azerbaijan': {'lat': 40.3769, 'lon': 49.8671, 'link': 'https://en.wikipedia.org/wiki/Baku_City_Circuit'},
    'Barhain': {'lat': 26.1351, 'lon': 50.5108, 'link': 'https://en.wikipedia.org/wiki/Bahrain_International_Circuit'},
    'Belgium': {'lat': 50.4372, 'lon': 5.9714, 'link': 'https://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps'},
    'Brazil': {'lat': -23.5505, 'lon': -46.2361, 'link': 'https://en.wikipedia.org/wiki/Interlagos'},
    'Canada': {'lat': 45.5017, 'lon': -73.5673, 'link': 'https://en.wikipedia.org/wiki/Gilles_Villeneuve_Circuit'},
    'China': {'lat': 31.3989, 'lon': 121.4565, 'link': 'https://en.wikipedia.org/wiki/Shanghai_International_Circuit'},
    'Emilia Romagna': {'lat': 44.3519, 'lon': 12.0412, 'link': 'https://en.wikipedia.org/wiki/Autodromo_Enzo_e_Dino_Ferrari'},
    'Great Britain': {'lat': 51.8042, 'lon': -0.3370, 'link': 'https://en.wikipedia.org/wiki/Silverstone_Circuit'},
    'Hungary': {'lat': 47.5811, 'lon': 19.2486, 'link': 'https://en.wikipedia.org/wiki/Hungaroring'},
    'Italy': {'lat': 45.6205, 'lon': 8.5874, 'link': 'https://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza'},
    'Japan': {'lat': 34.8431, 'lon': 135.7662, 'link': 'https://en.wikipedia.org/wiki/Suzuka_International_Racing_Course'},
    'Las Vegas': {'lat': 36.2744, 'lon': -115.1769, 'link': 'https://en.wikipedia.org/wiki/Las_Vegas_Grand_Prix'},
    'Mexico': {'lat': 19.4042, 'lon': -99.0955, 'link': 'https://en.wikipedia.org/wiki/Mexico_City_Grand_Prix'},
    'Miami': {'lat': 25.9506, 'lon': -80.2389, 'link': 'https://en.wikipedia.org/wiki/Miami_Grand_Prix'},
    'Monaco': {'lat': 43.7384, 'lon': 7.4246, 'link': 'https://en.wikipedia.org/wiki/Monaco_Grand_Prix'},
    'Netherland': {'lat': 52.3888, 'lon': 4.5411, 'link': 'https://en.wikipedia.org/wiki/Zandvoort_Circuit'},
    'Qatar': {'lat': 25.3548, 'lon': 51.4544, 'link': 'https://en.wikipedia.org/wiki/Lusail_International_Circuit'},
    'Saudi Arabia': {'lat': 26.4159, 'lon': 50.0877, 'link': 'https://en.wikipedia.org/wiki/Jeddah_Corniche_Circuit'},
    'Singapore': {'lat': 1.2914, 'lon': 103.8622, 'link': 'https://en.wikipedia.org/wiki/Marina_Bay_Street_Circuit'},
    'Spain': {'lat': 41.5699, 'lon': 1.8951, 'link': 'https://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya'},
}

tracks_coord = pd.DataFrame(circuits_coords).T.reset_index(names='track')
tracks_coord

,track,lat,lon,link
0,Abu Dhabi,24.4539,54.353,https://en.wikipedia.org/wiki/Yas_Marina_Circuit
1,Austin,30.1328,-97.6411,https://en.wikipedia.org/wiki/Circuit_of_the_A...
2,Australia,-37.815,144.968,https://en.wikipedia.org/wiki/Albert_Park_Circuit
3,Austria,47.2127,14.7675,https://en.wikipedia.org/wiki/Red_Bull_Ring
4,Azerbaijan,40.3769,49.8671,https://en.wikipedia.org/wiki/Baku_City_Circuit
5,Barhain,26.1351,50.5108,https://en.wikipedia.org/wiki/Bahrain_Internat...
6,Belgium,50.4372,5.9714,https://en.wikipedia.org/wiki/Circuit_de_Spa-F...
7,Brazil,-23.5505,-46.2361,https://en.wikipedia.org/wiki/Interlagos
8,Canada,45.5017,-73.5673,https://en.wikipedia.org/wiki/Gilles_Villeneuv...
9,China,31.3989,121.4565,https://en.wikipedia.org/wiki/Shanghai_Interna...
10,Emilia Romagna,44.3519,12.0412,https://en.wikipedia.org/wiki/Autodromo_Enzo_e...
11,Great Britain,51.8042,-0.337,https://en.wikipedia.org/wiki/Silverstone_Circuit
12,Hungary,47.5811,19.2486,https://en.wikipedia.org/wiki/Hungaroring
13,Italy,45.6205,8.5874,https://en.wikipedia.org/wiki/Autodromo_Nazion...
14,Japan,34.8431,135.7662,https://en.wikipedia.org/wiki/Suzuka_Internati...
15,Las Vegas,36.2744,-115.1769,https://en.wikipedia.org/wiki/Las_Vegas_Grand_...
16,Mexico,19.4042,-99.0955,https://en.wikipedia.org/wiki/Mexico_City_Gran...
17,Miami,25.9506,-80.2389,https://en.wikipedia.org/wiki/Miami_Grand_Prix
18,Monaco,43.7384,7.4246,https://en.wikipedia.org/wiki/Monaco_Grand_Prix
19,Netherland,52.3888,4.5411,https://en.wikipedia.org/wiki/Zandvoort_Circuit
20,Qatar,25.3548,51.4544,https://en.wikipedia.org/wiki/Lusail_Internati...
21,Saudi Arabia,26.4159,50.0877,https://en.wikipedia.org/wiki/Jeddah_Corniche_...
22,Singapore,1.2914,103.8622,https://en.wikipedia.org/wiki/Marina_Bay_Stree...
23,Spain,41.5699,1.8951,https://en.wikipedia.org/wiki/Circuit_de_Barce...

In [49]:
import plotly.express as px

fig = px.scatter_geo(tracks_coord,
               lat='lat',
               lon='lon',
               hover_name='track',
                projection='natural earth',
                     )

fig.update_traces(marker=dict(size=8))
fig.show()